DROP TABLE IF EXISTS events;

CREATE TABLE IF NOT EXISTS stats (
    id TEXT PRIMARY KEY,
    station TEXT NOT NULL,
    sensor TEXT NOT NULL,
    mean DOUBLE PRECISION NOT NULL,
    min DOUBLE PRECISION NOT NULL,
    max DOUBLE PRECISION NOT NULL,
    count BIGINT NOT NULL,
    timestamp BIGINT NOT NULL
);
